USE [MONTES]
GO
/****** Object:  Table [dbo].[Montes]    Script Date: 09/10/2023 13:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Montes](
	[CODIGO_MONTE] [int] NOT NULL,
	[COD_PROVINCIA] [varchar](2) NULL,
	[ESPACIO_NATURAL] [varchar](255) NULL,
	[SUPERFICIE] [real] NULL,
	[NUMERO_MONTES] [nchar](10) NULL,
 CONSTRAINT [PK_Montes] PRIMARY KEY CLUSTERED 
(
	[CODIGO_MONTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Provincias]    Script Date: 09/10/2023 13:57:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Provincias](
	[CODIGO] [varchar](2) NULL,
	[PROVINCIA] [varchar](40) NOT NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
