//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace farmacia
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProvincia
    {
        public tProvincia()
        {
            this.tLaboratorio = new HashSet<tLaboratorio>();
            this.tPaciente = new HashSet<tPaciente>();
        }
    
        public string Codigo { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<tLaboratorio> tLaboratorio { get; set; }
        public virtual ICollection<tPaciente> tPaciente { get; set; }
    }
}
