//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace farmacia
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUsuario
    {
        public string nif { get; set; }
        public string password { get; set; }
        public string rolName { get; set; }
    
        public virtual tRol tRol { get; set; }
    }
}
