//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace farmacia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GI1920Entities : DbContext
    {
        public GI1920Entities()
            : base("name=GI1920Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tLaboratorio> tLaboratorio { get; set; }
        public virtual DbSet<tPaciente> tPaciente { get; set; }
        public virtual DbSet<tPermiso> tPermiso { get; set; }
        public virtual DbSet<tProvincia> tProvincia { get; set; }
        public virtual DbSet<tReceta> tReceta { get; set; }
        public virtual DbSet<tRol> tRol { get; set; }
        public virtual DbSet<tUsuario> tUsuario { get; set; }
    }
}
