//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace farmacia
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPaciente
    {
        public tPaciente()
        {
            this.tReceta = new HashSet<tReceta>();
        }
    
        public string NIF { get; set; }
        public int NumSeguro { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Sexo { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Direccion { get; set; }
        public string Poblacion { get; set; }
        public string Provincia { get; set; }
        public string CodigoPostal { get; set; }
        public string Telefono { get; set; }
        public string e_mail { get; set; }
    
        public virtual tProvincia tProvincia { get; set; }
        public virtual ICollection<tReceta> tReceta { get; set; }
    }
}
