//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace farmacia
{
    using System;
    using System.Collections.Generic;
    
    public partial class tReceta
    {
        public int ID { get; set; }
        public string NIF { get; set; }
        public string PRODUCTO { get; set; }
        public string LABORATORIO { get; set; }
        public int UNIDADES { get; set; }
        public bool ENTREGADA { get; set; }
    
        public virtual tLaboratorio tLaboratorio { get; set; }
        public virtual tPaciente tPaciente { get; set; }
    }
}
