//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace farmacia
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRol
    {
        public tRol()
        {
            this.tPermiso = new HashSet<tPermiso>();
            this.tUsuario = new HashSet<tUsuario>();
        }
    
        public string rolName { get; set; }
        public string rolDes { get; set; }
        public bool admin { get; set; }
    
        public virtual ICollection<tPermiso> tPermiso { get; set; }
        public virtual ICollection<tUsuario> tUsuario { get; set; }
    }
}
